name: Verificação de Acessibilidade e SEO

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório do aluno
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar Lighthouse CI e HTMLHint
        run: |
          npm install -g @lhci/cli htmlhint

      - name: Rodar HTMLHint (Boas práticas de HTML)
        run: htmlhint index.html

      - name: Rodar Lighthouse CI
        run: lhci autorun --collect.staticDistDir=.
